# Generated by Django 4.1 on 2023-06-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_confignumbercards_difficult_confignumbercards_easy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confignumbercards',
            name='Difficult',
        ),
        migrations.RemoveField(
            model_name='configtimebonus',
            name='Difficult',
        ),
        migrations.AddField(
            model_name='confignumbercards',
            name='Hard',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configtimebonus',
            name='Hard',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confignumbercards',
            name='Easy',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='confignumbercards',
            name='Medium',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='configtimebonus',
            name='Easy',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='configtimebonus',
            name='Medium',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
