# Generated by Django 4.1 on 2023-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_confignumbercards_difficult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Difficulty', models.CharField(max_length=1)),
                ('PlayerName', models.CharField(max_length=30)),
                ('Score', models.PositiveIntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
