# Generated by Django 4.1 on 2023-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_highscore_savehighscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savehighscores',
            name='Difficulty',
            field=models.CharField(max_length=6),
        ),
    ]
