# Generated by Django 4.1 on 2023-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_savehighscores_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savehighscores',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
